package cz.muni.fi.pa036.betting.model;
// Generated 14.4.2015 11:34:11 by Hibernate Tools 4.3.1



/**
 * ContactUser generated by hbm2java
 */
public class ContactUser  implements java.io.Serializable {


     private ContactUserId id;
     private Contact contact;
     private User user;

    public ContactUser() {
    }

    public ContactUser(ContactUserId id, Contact contact, User user) {
       this.id = id;
       this.contact = contact;
       this.user = user;
    }
   
    public ContactUserId getId() {
        return this.id;
    }
    
    public void setId(ContactUserId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


