package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private int id;
     private String type;
     private String value;
     private Set<User> users = new HashSet<User>(0);

    public Contact() {
    }

	
    public Contact(int id, String type, String value) {
        this.id = id;
        this.type = type;
        this.value = value;
    }
    public Contact(int id, String type, String value, Set<User> users) {
       this.id = id;
       this.type = type;
       this.value = value;
       this.users = users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


