package cz.muni.fi.pa036.betting.model;
// Generated 14.4.2015 11:34:11 by Hibernate Tools 4.3.1



/**
 * ContactUserId generated by hbm2java
 */
public class ContactUserId  implements java.io.Serializable {


     private int id;
     private int contactid;
     private int userid;

    public ContactUserId() {
    }

    public ContactUserId(int id, int contactid, int userid) {
       this.id = id;
       this.contactid = contactid;
       this.userid = userid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getContactid() {
        return this.contactid;
    }
    
    public void setContactid(int contactid) {
        this.contactid = contactid;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContactUserId) ) return false;
		 ContactUserId castOther = ( ContactUserId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getContactid()==castOther.getContactid())
 && (this.getUserid()==castOther.getUserid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getContactid();
         result = 37 * result + this.getUserid();
         return result;
   }   


}


