package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1



/**
 * EventCompetitor generated by hbm2java
 */
public class EventCompetitor  implements java.io.Serializable {


     private EventCompetitorId id;
     private Competitor competitor;
     private Event event;
     private double odds;

    public EventCompetitor() {
    }

    public EventCompetitor(EventCompetitorId id, Competitor competitor, Event event, double odds) {
       this.id = id;
       this.competitor = competitor;
       this.event = event;
       this.odds = odds;
    }
   
    public EventCompetitorId getId() {
        return this.id;
    }
    
    public void setId(EventCompetitorId id) {
        this.id = id;
    }
    public Competitor getCompetitor() {
        return this.competitor;
    }
    
    public void setCompetitor(Competitor competitor) {
        this.competitor = competitor;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public double getOdds() {
        return this.odds;
    }
    
    public void setOdds(double odds) {
        this.odds = odds;
    }




}


