package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sport generated by hbm2java
 */
public class Sport  implements java.io.Serializable {


     private int id;
     private String kindofsport;
     private Set<UserFavoriteSport> userFavoriteSports = new HashSet<UserFavoriteSport>(0);
     private Set<Competitor> competitors = new HashSet<Competitor>(0);
     private Set<League> leagues = new HashSet<League>(0);

    public Sport() {
    }

	
    public Sport(int id, String kindofsport) {
        this.id = id;
        this.kindofsport = kindofsport;
    }
    public Sport(int id, String kindofsport, Set<UserFavoriteSport> userFavoriteSports, Set<Competitor> competitors, Set<League> leagues) {
       this.id = id;
       this.kindofsport = kindofsport;
       this.userFavoriteSports = userFavoriteSports;
       this.competitors = competitors;
       this.leagues = leagues;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getKindofsport() {
        return this.kindofsport;
    }
    
    public void setKindofsport(String kindofsport) {
        this.kindofsport = kindofsport;
    }
    public Set<UserFavoriteSport> getUserFavoriteSports() {
        return this.userFavoriteSports;
    }
    
    public void setUserFavoriteSports(Set<UserFavoriteSport> userFavoriteSports) {
        this.userFavoriteSports = userFavoriteSports;
    }
    public Set<Competitor> getCompetitors() {
        return this.competitors;
    }
    
    public void setCompetitors(Set<Competitor> competitors) {
        this.competitors = competitors;
    }
    public Set<League> getLeagues() {
        return this.leagues;
    }
    
    public void setLeagues(Set<League> leagues) {
        this.leagues = leagues;
    }




}


