package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Status() {
    }

	
    public Status(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Status(int id, String name, Set<Ticket> tickets) {
       this.id = id;
       this.name = name;
       this.tickets = tickets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}


