package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1



/**
 * TicketEvent generated by hbm2java
 */
public class TicketEvent  implements java.io.Serializable {


     private TicketEventId id;
     private Competitor competitor;
     private Event event;
     private Ticket ticket;
     private double betvalue;

    public TicketEvent() {
    }

	
    public TicketEvent(TicketEventId id, Event event, Ticket ticket, double betvalue) {
        this.id = id;
        this.event = event;
        this.ticket = ticket;
        this.betvalue = betvalue;
    }
    public TicketEvent(TicketEventId id, Competitor competitor, Event event, Ticket ticket, double betvalue) {
       this.id = id;
       this.competitor = competitor;
       this.event = event;
       this.ticket = ticket;
       this.betvalue = betvalue;
    }
   
    public TicketEventId getId() {
        return this.id;
    }
    
    public void setId(TicketEventId id) {
        this.id = id;
    }
    public Competitor getCompetitor() {
        return this.competitor;
    }
    
    public void setCompetitor(Competitor competitor) {
        this.competitor = competitor;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public double getBetvalue() {
        return this.betvalue;
    }
    
    public void setBetvalue(double betvalue) {
        this.betvalue = betvalue;
    }




}


