package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private int id;
     private Status status;
     private User user;
     private Date dateofcreated;
     private double deposit;
     private Date dateofclosed;
     private Set<TicketEvent> ticketEvents = new HashSet<TicketEvent>(0);

    public Ticket() {
    }

	
    public Ticket(int id, Status status, User user, Date dateofcreated, double deposit) {
        this.id = id;
        this.status = status;
        this.user = user;
        this.dateofcreated = dateofcreated;
        this.deposit = deposit;
    }
    public Ticket(int id, Status status, User user, Date dateofcreated, double deposit, Date dateofclosed, Set<TicketEvent> ticketEvents) {
       this.id = id;
       this.status = status;
       this.user = user;
       this.dateofcreated = dateofcreated;
       this.deposit = deposit;
       this.dateofclosed = dateofclosed;
       this.ticketEvents = ticketEvents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDateofcreated() {
        return this.dateofcreated;
    }
    
    public void setDateofcreated(Date dateofcreated) {
        this.dateofcreated = dateofcreated;
    }
    public double getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(double deposit) {
        this.deposit = deposit;
    }
    public Date getDateofclosed() {
        return this.dateofclosed;
    }
    
    public void setDateofclosed(Date dateofclosed) {
        this.dateofclosed = dateofclosed;
    }
    public Set<TicketEvent> getTicketEvents() {
        return this.ticketEvents;
    }
    
    public void setTicketEvents(Set<TicketEvent> ticketEvents) {
        this.ticketEvents = ticketEvents;
    }




}


