package cz.muni.fi.pa036.betting.model;
// Generated 14.4.2015 11:34:11 by Hibernate Tools 4.3.1



/**
 * TicketEvent generated by hbm2java
 */
public class TicketEvent  implements java.io.Serializable {


     private TicketEventId id;
     private Event event;
     private Ticket ticket;
     private int betoption;
     private double betvalue;

    public TicketEvent() {
    }

    public TicketEvent(TicketEventId id, Event event, Ticket ticket, int betoption, double betvalue) {
       this.id = id;
       this.event = event;
       this.ticket = ticket;
       this.betoption = betoption;
       this.betvalue = betvalue;
    }
   
    public TicketEventId getId() {
        return this.id;
    }
    
    public void setId(TicketEventId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public int getBetoption() {
        return this.betoption;
    }
    
    public void setBetoption(int betoption) {
        this.betoption = betoption;
    }
    public double getBetvalue() {
        return this.betvalue;
    }
    
    public void setBetvalue(double betvalue) {
        this.betvalue = betvalue;
    }




}


