package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.joda.time.DateTime;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {

    
     private int id;
     private Status status;
     private User user;
     private DateTime dateofcreated;
     private double deposit;
     private DateTime dateofclosed;
     private Set<TicketEvent> ticketEvents = new HashSet<TicketEvent>(0);

    public Ticket() {
    }

	
    public Ticket(int id, Status status, User user, DateTime dateofcreated, double deposit) {
        this.id = id;
        this.status = status;
        this.user = user;
        this.dateofcreated = dateofcreated;
        this.deposit = deposit;
    }
    public Ticket(int id, Status status, User user, DateTime dateofcreated, double deposit, DateTime dateofclosed, Set<TicketEvent> ticketEvents) {
       this.id = id;
       this.status = status;
       this.user = user;
       this.dateofcreated = dateofcreated;
       this.deposit = deposit;
       this.dateofclosed = dateofclosed;
       this.ticketEvents = ticketEvents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public DateTime getDateofcreated() {
        return this.dateofcreated;
    }
    
    public void setDateofcreated(DateTime dateofcreated) {
        this.dateofcreated = dateofcreated;
    }
    public double getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(double deposit) {
        this.deposit = deposit;
    }
    public DateTime getDateofclosed() {
        return this.dateofclosed;
    }
    
    public void setDateofclosed(DateTime dateofclosed) {
        this.dateofclosed = dateofclosed;
    }
    public Set<TicketEvent> getTicketEvents() {
        return this.ticketEvents;
    }
    
    public void setTicketEvents(Set<TicketEvent> ticketEvents) {
        this.ticketEvents = ticketEvents;
    }

    public int getTicketEventsCount() {
        return this.ticketEvents.size();
    }

    public double getTotalTicketOdds() {
        double result = 1;
        for (TicketEvent ticketEvent : ticketEvents) {
            result *= ticketEvent.getBetvalue();
        }
        return result;
    }
    
    public double getTotalWonMoney() {
        double result = 0;
        if (this.status.getId() == Status.STATUS_WINNING) {
            result = this.deposit * getTotalTicketOdds();
        }
        return result;
    }

}


