package cz.muni.fi.pa036.betting.model;
// Generated 14.4.2015 11:34:11 by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private UserRoleId id;
     private Role role;
     private User user;

    public UserRole() {
    }

    public UserRole(UserRoleId id, Role role, User user) {
       this.id = id;
       this.role = role;
       this.user = user;
    }
   
    public UserRoleId getId() {
        return this.id;
    }
    
    public void setId(UserRoleId id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


