package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String login;
     private String password;
     private String name;
     private String surname;
     private Date dateofbirth;
     private Date datelastlogin;
     private double balance;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);
     private Set<UserFavoriteSport> userFavoriteSports = new HashSet<UserFavoriteSport>(0);
     private Set<Contact> contacts = new HashSet<Contact>(0);
     private Set<Role> roles = new HashSet<Role>(0);

    public User() {
    }

	
    public User(int id, String login, String password, String name, String surname, Date dateofbirth, Date datelastlogin, double balance) {
        this.id = id;
        this.login = login;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.dateofbirth = dateofbirth;
        this.datelastlogin = datelastlogin;
        this.balance = balance;
    }
    public User(int id, String login, String password, String name, String surname, Date dateofbirth, Date datelastlogin, double balance, Set<Ticket> tickets, Set<UserFavoriteSport> userFavoriteSports, Set<Contact> contacts, Set<Role> roles) {
       this.id = id;
       this.login = login;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.dateofbirth = dateofbirth;
       this.datelastlogin = datelastlogin;
       this.balance = balance;
       this.tickets = tickets;
       this.userFavoriteSports = userFavoriteSports;
       this.contacts = contacts;
       this.roles = roles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public Date getDatelastlogin() {
        return this.datelastlogin;
    }
    
    public void setDatelastlogin(Date datelastlogin) {
        this.datelastlogin = datelastlogin;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }
    public Set<UserFavoriteSport> getUserFavoriteSports() {
        return this.userFavoriteSports;
    }
    
    public void setUserFavoriteSports(Set<UserFavoriteSport> userFavoriteSports) {
        this.userFavoriteSports = userFavoriteSports;
    }
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }


    public boolean getIsUserAdmin() {
        return (roles != null && roles.contains(Role.ROLE_SUPERADMIN));
    }
    
    public boolean getIsUserBookmaker() {
        return (roles != null && roles.contains(Role.ROLE_BOOKMAKER));
    }
    
    @Override
    public String toString(){
        return "name: " + name + " surname " + surname; 
    }
            
}


