package cz.muni.fi.pa036.betting.model;
// Generated 14.4.2015 11:34:11 by Hibernate Tools 4.3.1



/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleId  implements java.io.Serializable {


     private int id;
     private int userid;
     private int roleid;

    public UserRoleId() {
    }

    public UserRoleId(int id, int userid, int roleid) {
       this.id = id;
       this.userid = userid;
       this.roleid = roleid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRoleId) ) return false;
		 UserRoleId castOther = ( UserRoleId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUserid()==castOther.getUserid())
 && (this.getRoleid()==castOther.getRoleid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUserid();
         result = 37 * result + this.getRoleid();
         return result;
   }   


}


