package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1



/**
 * UserFavoriteSportId generated by hbm2java
 */
public class UserFavoriteSportId  implements java.io.Serializable {


     private int userid;
     private int sportid;

    public UserFavoriteSportId() {
    }

    public UserFavoriteSportId(int userid, int sportid) {
       this.userid = userid;
       this.sportid = sportid;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getSportid() {
        return this.sportid;
    }
    
    public void setSportid(int sportid) {
        this.sportid = sportid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserFavoriteSportId) ) return false;
		 UserFavoriteSportId castOther = ( UserFavoriteSportId ) other; 
         
		 return (this.getUserid()==castOther.getUserid())
 && (this.getSportid()==castOther.getSportid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserid();
         result = 37 * result + this.getSportid();
         return result;
   }   


}


