package cz.muni.fi.pa036.betting.model;
// Generated 18.4.2015 11:47:24 by Hibernate Tools 4.3.1



/**
 * UserFavoriteSport generated by hbm2java
 */
public class UserFavoriteSport  implements java.io.Serializable {


     private UserFavoriteSportId id;
     private Sport sport;
     private User user;
     private int priority;

    public UserFavoriteSport() {
    }

    public UserFavoriteSport(UserFavoriteSportId id, Sport sport, User user, int priority) {
       this.id = id;
       this.sport = sport;
       this.user = user;
       this.priority = priority;
    }
   
    public UserFavoriteSportId getId() {
        return this.id;
    }
    
    public void setId(UserFavoriteSportId id) {
        this.id = id;
    }
    public Sport getSport() {
        return this.sport;
    }
    
    public void setSport(Sport sport) {
        this.sport = sport;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }




}


